### ISSUE TITLE
CCH ucjeps color issues

### ISSUE THREAD

**Issue by jdeck88** [BNHM/berkeleymapper#65]
From staci markos:
We need your help solving a problem with Berkeley Mapper.

Dick noticed that one of our regions isn’t displaying the correct color in the Berkeley Mapper displays.

I have attached a screen shot — see that region southeast of Paso Robles? It is supposed to be the same color as the region where Paso Robles is (ScoR). 

I’ve attached what I think are the most recent files that we’ve sent to you. 
[cfp_baja.zip](https://github.com/BNHM/berkeleymapper/files/335898/cfp_baja.zip)

![screen shot 2016-06-27 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/1154501/16396995/9d9b2fc0-3c76-11e6-9df1-ac31c87cd4fa.png)

[cfp_baja_kmz.kmz.zip](https://github.com/BNHM/berkeleymapper/files/335900/cfp_baja_kmz.kmz.zip)

**Comment by jdeck88** [comment]
I spent a bunch of time looking at this today.  

The KML file showing the ecoregions is good.  it displays fine in Google Earth, behaves fine when importing to Fusion tables and in Mymaps.google.com... However, when accessing via the API, you are correct, the SCoR region is incorrectly displayed with the wrong color (and when clicking on it comes up as SnJV).  Am at a loss of how to fix this.

I did explore one work-around which works... importing the layer into Google Fusion Tables...
I  hooked up a sample fusion table into BerkeleyMapper (taking the liberty of adding it to the ucjeps.xml configuration file) and saw that the polygons are all correct.. That is, the polygon came up as SCoR instead of SnJV when clicked.  However, as you may notice.. the colors are ALL RED.  I did change the colors of the polygons to the proper colors but i believe google is caching the results.  or, maybe the styling on the fusion table version is not coming through the way it should.  

At any rate, assuming i can get the styling fixed, let me know if you want to go the fusion table route... i may choose to put more Berkeleymapper layers into fusion tables....

**Comment by jdeck88** [comment]
Oh, just fixed the color/styling issue.  It now displays colors! However, the mapping i did from RGB to HEX was woefully awful.  Sorry about that... anyone want to volunteer to fix up some colors, coding RGB to proper Hex?

**Comment by UC-JepsonHerbaria** [comment]
Hi John, Staci and Michelle,

You can make this Berkeley Mapper issue resolved.  In trying to fix the xml files to reflect the changes in necessary because Joyce moved the UCJEPS web pages over to a secure server, I noticed this issue.  I was not even aware of this problem previously.

I fixed it.  It turns out that the the SCoRI segment in question overlies a portion of SnJV polygon that was continuous underneath that segment.  The light yellow color of the underlying polygon was coloring the upper SCoRI layer because every polygon is set to a 50% transparency in the kmz file.   I used my revised jepson regions shapefile  and made a kml file of just the SnJV polygon.  My file has the smaller SCoRI polygon cut away from the larger SnJV polygon.  I then cut and pasted the polygon coordinates section from the new SnJV kml into the appropriate section of the old jepcodes-v7.kmz file.  The maps on the eFlora now have the correct color for this small segment of SCoRI due to not having a light yellowish-green underlayer of SnJV.

Jason Alexander

**Comment by jdeck88** [comment]
ok, cool!

John
